minio:
  url: https://file.quizzy.it.com/
  access-key: admin
  secret-key: admin123
  bucket: products
spring:
  application:
    name: devsolve-api
  jpa:
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB
  datasource:
    username: devsolve
    driver-class-name: org.postgresql.Driver
    password: qwer
    url: jdbc:postgresql://localhost:8989/devsolve
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.quizzy.it.com/realms/devsolve
server:
  port: 8999
keycloak:
  server-url: https://auth.quizzy.it.com/
  realm: devsolve
  client-id: devsolve-admin
  client-secret: 9eYFasE8u0SlhhkF7cqCZs8on1fAmUlY
  target-realm: devsolve