spring:
  application:
    name: devsolve-api

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: false

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      separator: "^^^"

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}

server:
  port: 8999

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  target-realm: ${KEYCLOAK_TARGET_REALM}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
